serverinfo:
  servers:
    - serverName: Windows Server
      ipAddress: 192.168.1.1
      username: admin
      password: admin
    - serverName: Unix Server
      ipAddress: 127.0.0.1
      username: arsen
      password: 1298
